volumes:
     app-volume:

networks:
  specify:
    driver: bridge

services:
  webportal:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - specify
    restart: always
    volumes:
      #- /klib/app/docker/specify-web-portal/specify_exports/export.zip:/home/specify/webportal-installer/specify_exports/export.zip
      - app-volume:/home/specify


  web:
    image: nginx
    networks:
      - specify
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./webportal-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app-volume:/home/specify
    depends_on:
      - webportal
